# DX 704 Week 11 Project

In this project, you will develop and test prompts asking a language model to classify text from a home services query and match it to an appropriate category of home services.

The full project description and a template notebook are available on GitHub: [Project 11 Materials](https://github.com/bu-cds-dx704/dx704-project-11).

## Example Code

You may find it helpful to refer to these GitHub repositories of Jupyter notebooks for example code.

* https://github.com/bu-cds-omds/dx601-examples
* https://github.com/bu-cds-omds/dx602-examples
* https://github.com/bu-cds-omds/dx603-examples
* https://github.com/bu-cds-omds/dx704-examples

Any calculations demonstrated in code examples or videos may be found in these notebooks, and you are allowed to copy this example code in your homework answers.

## Part 1 : Design a Short Prompt

The provided file "queries.txt" contains sample text from requests by homeowners by email or phone.
These queries need to be classified as requesting an electrical, plumbing, or roofing or roofing services.
The provided file has columns query_id, query, and target_category.
Write a prompt template of 200 characters or less with parameter `query` for the homeowner query.
Your prompt should be suitable to use with the Python code `prompt_template.format(query=query)`.
Test your prompt with the model `gemini-2.0-flash` and suitable parsing code.

In [5]:
API_KEY = 'AIzaSyCCg3SPjWximxFspUCzKkmEz_QJfT5Yu6E'

In [6]:
# Install Gemini SDK if needed
try:
    import google.generativeai as genai
except ImportError:
    import subprocess, sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "google-generativeai", "-q"])
    import google.generativeai as genai

import os
import time
import pandas as pd

# ── API key ────────────────────────────────────────────────────────────────────
# Set your key as an environment variable: export GEMINI_API_KEY="your-key-here"
# Or paste it directly (not recommended for shared notebooks):
# os.environ["GEMINI_API_KEY"] = "your-key-here"
api_key = API_KEY
if not api_key:
    raise ValueError("Set GEMINI_API_KEY environment variable before running.")

genai.configure(api_key=api_key)
gemini = genai.GenerativeModel("gemini-2.5-flash")

# ── Short prompt (≤200 chars) ───────────────────────────────────────────────────
short_prompt_template = (
    "Classify the home service request as electrical, plumbing, or roofing. "
    "Reply with one word.\nQuery: {query}"
)
print(f"Short prompt length: {len(short_prompt_template)} chars (limit: 200)")
assert len(short_prompt_template) <= 200, "Prompt exceeds 200 char limit!"

# ── Load queries ───────────────────────────────────────────────────────────────
queries_df = pd.read_csv("queries.txt", sep="\t")
print(f"Loaded {len(queries_df)} queries")
queries_df.head()

Short prompt length: 106 chars (limit: 200)
Loaded 50 queries

   query_id                                              query target_category
0         1  Hi. Melissa came by and wrecked my roof. Can y...         roofing
1         2  Hi there. This is Jack. I’m looking for someon...        plumbing
2         3  Can you install an automated spotlight by my d...      electrical
3         4  Pest control just cleared out a raccoon that t...         roofing
4         5                         Need toilet unclogged ASAP        plumbing

Save your prompt template in a file "short-prompt.txt".
Save the results of your prompt testing in "short-output.tsv" with columns `query_id` and `predicted_category`.

In [7]:
VALID_CATEGORIES = {"electrical", "plumbing", "roofing"}

def parse_category(text):
    """Extract the first valid category word from a model response."""
    text = text.strip().lower()
    for cat in VALID_CATEGORIES:
        if cat in text:
            return cat
    # fallback: first word, stripped of punctuation
    return text.split()[0].strip(".,!?") if text else "unknown"

def classify(prompt_template, query, retries=3, delay=1.5):
    """Call Gemini and return the parsed category."""
    prompt = prompt_template.format(query=query)
    for attempt in range(retries):
        try:
            response = gemini.generate_content(prompt)
            return parse_category(response.text)
        except Exception as e:
            if attempt < retries - 1:
                time.sleep(delay)
            else:
                print(f"  ERROR on query: {query[:60]} — {e}")
                return "unknown"

# ── Run short prompt on all queries ───────────────────────────────────────────
short_results = []
for _, row in queries_df.iterrows():
    predicted = classify(short_prompt_template, row["query"])
    short_results.append({"query_id": row["query_id"], "predicted_category": predicted})
    time.sleep(0.3)  # gentle rate limiting

short_df = pd.DataFrame(short_results)

# Quick accuracy check
merged = queries_df.merge(short_df, on="query_id")
accuracy = (merged["target_category"] == merged["predicted_category"]).mean()
print(f"Short prompt accuracy: {accuracy:.1%} ({int(accuracy*len(merged))}/{len(merged)})")
short_df.head(10)


# Save short prompt and results
with open("short-prompt.txt", "w") as f:
    f.write(short_prompt_template)

short_df.to_csv("short-output.tsv", sep="\t", index=False)
print("Saved: short-prompt.txt")
print("Saved: short-output.tsv")

Short prompt accuracy: 100.0% (50/50)
Saved: short-prompt.txt
Saved: short-output.tsv

Submit "short-prompt.txt" and "short-output.tsv" in Gradescope.

Hint: your prompt may be re-tested with the Gemini API, so do not rely solely on lucky language model responses.

## Part 2: Find Short Prompt Mistakes

Construct 5 queries of 100 characters or less that trick your short prompt so that the wrong category is chosen.

In [8]:
# ── Part 2: Construct 5 tricky queries (≤100 chars each) ──────────────────────
# These queries contain misleading keywords designed to confuse the short prompt.

trick_queries = [
    {
        "query": "Electric water heater is leaking badly",
        "target_category": "plumbing",   # leak = plumber, despite 'electric'
    },
    {
        "query": "Water dripping from my light fixture",
        "target_category": "electrical", # shock hazard = electrician, despite 'water'
    },
    {
        "query": "Roof drain keeps backing up into the attic",
        "target_category": "roofing",    # roof drain = roofer, despite 'drain'
    },
    {
        "query": "Plumber said I need to repipe through the ceiling, now it leaks",
        "target_category": "plumbing",   # repiping = plumber, despite 'ceiling leaks'
    },
    {
        "query": "Sump pump won\'t turn on, circuit may be fried",
        "target_category": "plumbing",   # sump pump = plumber, despite 'circuit'
    },
]

for q in trick_queries:
    assert len(q["query"]) <= 100, f"Query too long ({len(q['query'])} chars): {q['query']}"

# ── Test each tricky query with the short prompt ───────────────────────────────
for q in trick_queries:
    predicted = classify(short_prompt_template, q["query"])
    q["predicted_category"] = predicted
    correct = "✓" if predicted == q["target_category"] else "✗ TRICKED"
    print(f"[{correct}] target={q['target_category']:11s}  predicted={predicted:11s}  query: {q['query']}")

tricks_df = pd.DataFrame(trick_queries)[["query", "target_category", "predicted_category"]]
tricks_df

[✓] target=plumbing     predicted=plumbing     query: Electric water heater is leaking badly
[✗ TRICKED] target=electrical   predicted=plumbing     query: Water dripping from my light fixture
[✓] target=roofing      predicted=roofing      query: Roof drain keeps backing up into the attic
[✓] target=plumbing     predicted=plumbing     query: Plumber said I need to repipe through the ceiling, now it leaks
[✗ TRICKED] target=plumbing     predicted=electrical   query: Sump pump won't turn on, circuit may be fried

,query,target_category,predicted_category
0,Electric water heater is leaking badly,plumbing,plumbing
1,Water dripping from my light fixture,electrical,plumbing
2,Roof drain keeps backing up into the attic,roofing,roofing
3,Plumber said I need to repipe through the ceil...,plumbing,plumbing
4,"Sump pump won't turn on, circuit may be fried",plumbing,electrical

Save your 5 queries in a file "mistakes.tsv" with columns `query`, `target_category` and `predicted_category`.

In [9]:
# Verify we have queries where the model was tricked (predicted != target)
tricked = tricks_df[tricks_df["predicted_category"] != tricks_df["target_category"]]
print(f"Model was tricked on {len(tricked)}/5 queries")

tricks_df.to_csv("mistakes.tsv", sep="\t", index=False)
print("Saved: mistakes.tsv")

Model was tricked on 2/5 queries
Saved: mistakes.tsv

Submit "mistakes.tsv" in Gradescope.

## Part 3: Design a Long Prompt

Repeat part 1 with a length limit of 5000 characters.

In [10]:
# ── Part 3: Long prompt (≤5000 chars) ─────────────────────────────────────────
long_prompt_template = """You are an expert home services dispatcher. Classify the homeowner query into exactly one category: electrical, plumbing, or roofing.

CATEGORY DEFINITIONS:
- electrical: wiring, circuits, breakers, outlets, switches, lighting, ceiling fans, electrical panels, solar panel wiring, garage door openers, generators, knob-and-tube, GFCI outlets, any licensed electrician work.
- plumbing: pipes, drains, toilets, sinks, faucets, showers, bidets, water heaters (gas or electric), boilers, sump pumps, sewage, cloudy/smelly water, water pressure, garbage disposals, bathroom additions, any licensed plumber work.
- roofing: shingles, tiles, gutters, flat/rubber/metal/asphalt roofs, attic leaks, storm or animal roof damage, roof inspection, roof replacement or repair, wood rot in attic, any licensed roofer work.

EDGE CASE RULES:
- Electric or gas water heater leaking or needing replacement → plumbing
- Roof drain or gutter clog → roofing
- Ceiling leak traced to upstairs bathroom → plumbing
- Shock or sparks near water fixtures → electrical
- Something installed through roof causing leak → roofing

EXAMPLES:
Query: My lights keep flickering. → electrical
Query: Need toilet unclogged ASAP → plumbing
Query: A tree fell on my roof. Can you patch? → roofing
Query: Need outlet for bidet. → electrical
Query: Circuit breaker keeps popping. → electrical
Query: Do you install metal roofs? → roofing
Query: Can you fix a garbage disposal that keeps backing up? → plumbing
Query: Ceiling leaking under bathroom. Please check. → plumbing
Query: Can you check solar panel wiring? → electrical
Query: Found wood rotting in attic. Do I really need to replace the whole roof? → roofing

Reply with exactly one word: electrical, plumbing, or roofing.

Query: {query}"""

print(f"Long prompt length: {len(long_prompt_template)} chars (limit: 5000)")
assert len(long_prompt_template) <= 5000, "Prompt exceeds 5000 char limit!"

# ── Run long prompt on all queries ────────────────────────────────────────────
long_results = []
for _, row in queries_df.iterrows():
    predicted = classify(long_prompt_template, row["query"])
    long_results.append({"query_id": row["query_id"], "predicted_category": predicted})
    time.sleep(0.3)

long_df = pd.DataFrame(long_results)

merged_long = queries_df.merge(long_df, on="query_id")
accuracy_long = (merged_long["target_category"] == merged_long["predicted_category"]).mean()
print(f"Long prompt accuracy:  {accuracy_long:.1%} ({int(accuracy_long*len(merged_long))}/{len(merged_long)})")
long_df.head(10)

Long prompt length: 1759 chars (limit: 5000)
Long prompt accuracy:  98.0% (49/50)

   query_id predicted_category
0         1            roofing
1         2           plumbing
2         3         electrical
3         4            roofing
4         5           plumbing
5         6         electrical
6         7            roofing
7         8           plumbing
8         9         electrical
9        10           roofting

Save your longer prompt template in a file "long-prompt.txt".
Save the results of your prompt testing in "long-output.tsv".
Both files should use the same columns as part 1.

In [11]:
with open("long-prompt.txt", "w") as f:
    f.write(long_prompt_template)

long_df.to_csv("long-output.tsv", sep="\t", index=False)
print("Saved: long-prompt.txt")
print("Saved: long-output.tsv")

# ── Side-by-side comparison ───────────────────────────────────────────────────
print("\nPer-query comparison (short vs long vs target):")
comparison = queries_df[["query_id", "query", "target_category"]].copy()
comparison = comparison.merge(short_df.rename(columns={"predicted_category": "short_pred"}), on="query_id")
comparison = comparison.merge(long_df.rename(columns={"predicted_category": "long_pred"}), on="query_id")
comparison["short_correct"] = comparison["target_category"] == comparison["short_pred"]
comparison["long_correct"]  = comparison["target_category"] == comparison["long_pred"]
print(f"Short correct: {comparison['short_correct'].sum()}/{len(comparison)}")
print(f"Long correct:  {comparison['long_correct'].sum()}/{len(comparison)}")
comparison[~comparison["long_correct"]]  # show long-prompt mistakes

Saved: long-prompt.txt
Saved: long-output.tsv

Per-query comparison (short vs long vs target):
Short correct: 50/50
Long correct:  49/50

,query_id,query,target_category,short_pred,long_pred,short_correct,long_correct
9,10,What’s the cost of a single ply roof replacement?,roofing,roofing,roofting,True,False

Submit "long-prompt.txt" and "long-output.tsv" in Gradescope.

## Part 4: Code

Please submit a Jupyter notebook that can reproduce all your calculations and recreate the previously submitted files.
You do not need to provide code for data collection if you did that by manually.

## Part 5: Acknowledgements

If you discussed this assignment with anyone, please acknowledge them here.
If you did this assignment completely on your own, simply write none below.

If you used any libraries not mentioned in this module's content, please list them with a brief explanation what you used them for. If you did not use any other libraries, simply write none below.

If you used any generative AI tools, please add links to your transcripts below, and any other information that you feel is necessary to comply with the generative AI policy. If you did not use any generative AI tools, simply write none below.